apiVersion: v1
kind: Service
metadata:
  name: studysync-core
spec:
  type: NodePort
  selector:
    app: studysync-core
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30090   # أو سيبها فاضية وK8s يختار رقم بين 30000-32767
