apiVersion: apps/v1
kind: Deployment
metadata:
  name: studysync-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studysync-core
  template:
    metadata:
      labels:
        app: studysync-core
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo "‚è≥ Waiting for MySQL..."; sleep 2; done']
      containers:
        - name: studysync-core
          image: ayahosny/studysync-core:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_HOST
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASSWORD
